### ISSUE TITLE
ImportError: No module named LibRadar.libradar

### ISSUE THREAD

**Issue by singhaniashrinkhala** [pkumza/LibRadar#22]
I have successfully installed LibRadar.

My script looks like this:

```
from LibRadar.libradar import LibRadar
from collections import defaultdict
output = defaultdict(list)

if __name__ == '__main__':
        for dirname, dirnames, filenames in os.walk('..\download'):
.........
```
However, when I try running it, I get this:

Traceback (most recent call last):
  File "script.py", line 4, in <module>
    from LibRadar.libradar import LibRadar
ImportError: No module named LibRadar.libradar

Not sure why.

**Comment by pkumza** [comment]
Maybe you could try the source code in release of version 2.1 first




On 03/13/2017 08:14, fringi wrote:

I have successfully installed LibRadar.

My script looks like this:

from LibRadar.libradar import LibRadar
from collections import defaultdict
output = defaultdict(list)

if __name__ == '__main__':
        for dirname, dirnames, filenames in os.walk('..\download'):
.........


However, when I try running it, I get this:

Traceback (most recent call last):
File "script.py", line 4, in
from LibRadar.libradar import LibRadar
ImportError: No module named LibRadar.libradar

Not sure why.

**Comment by singhaniashrinkhala** [comment]
i didn't get you

**Comment by pkumza** [comment]
Github has a release tab for this repo


发自网易邮箱大师
On 03/13/2017 08:40, fringi wrote:

i didn't get you

**Comment by pkumza** [comment]
Oh, I know what you got.
You tried use LibRadar as a module.

if you want to use 'from LibRadar.libradar import LibRadar', you'd better know how to use 'from future import absolute_import' first.
