### ISSUE TITLE
LibRadarData.rdb 404 Not Find

### ISSUE THREAD

**Issue by QyMars** [pkumza/LibRadar#24]
Hello @pkumza. I run the tool with setps you provide. but the link for LibRaderData.rdb is dead. 
this file is not find. 
Can you send it to my mailbox or rebuild the link? My emali is qiuyu93422@163.com
I look forward to receiving your reply as soon as possible. Thank you.

**Comment by pkumza** [comment]
I will sent one to your email tomorrow.




发自网易邮箱大师
On 04/12/2017 21:59, QyMars wrote:

Hello @pkumza. I run the tool with setps you provide. but the link for LibRaderData.rdb is dead.
this file is not find.
Can you send it to my mailbox or rebuild the link? My emali is qiuyu93422@163.com
I look forward to receiving your reply as soon as possible. Thank you.

**Comment by IzzySoft** [comment]
@pkumza if the link is dead, you should fix that as well – without the database the tool isn't very useful I'd say :stuck_out_tongue_winking_eye:

**Comment by pkumza** [comment]
Nice suggestion! I will.☕️


On 04/13/2017 00:01, Izzy wrote:

@pkumza if the link is dead, you should fix that as well – without the database the tool isn't very useful I'd say 😜

**Comment by tmliu0606** [comment]
Hey@pkumza, I'm a BUPT student and I need LibRaderData.rdb as well. Can you send it to my Email?Mine is tmliu@bupt.edu.cn. Looking forward to your reply as soon as possible. Thank you.

**Comment by pkumza** [comment]
## Solved!

**Comment by LL-loveshrimp** [comment]
Hello@pkumza! I have a homework about Apk analysis  and i need LibRaderData.rdb . Can you send it to my mailbox ？Mine is pfjenny@bupt.edu.cn. Looking forward to your reply as soon as possible. Thank you very much.
