### ISSUE TITLE
How can I use LibRadar to delete the thrid-party librarys in batches? 

### ISSUE THREAD

**Issue by tmliu0606** [pkumza/LibRadar#25]
Hello@pkumza  I'm trying to delete these libs from my apks, can I use LibRadar to do that?

**Comment by pkumza** [comment]
I used to support this functionality in version 1.
As LibRadar goes to version2, dex analysis is used to replace smali analysis. It becomes harder to implement deletion operation on dex files.


You could export a list of package names of suspicious libraries with LibRadar. Then decompile the apk with Apktool, at last remove the libraries in the list and you will get the core smali code writen by the developer.


On 04/17/2017 15:03, tmliu0606 wrote:

Hello@pkumza I'm trying to delete these libs from my apks, can I use LibRadar to do that?

**Comment by tmliu0606** [comment]
Thanks for your help . I will try the Version 1.

**Comment by tmliu0606** [comment]
@pkumza  I'm using Version 1 and set RM_STATUS to 1, it didn't delete the libs, why is that?

**Comment by pkumza** [comment]
Try [commit 6b2115] and set RM_STATUS to 2.

**Comment by pkumza** [comment]
Just change code of main/detect.py(around line 400) to:

```
if RM_STATUS == 1: 
            cmd = 'rm -rf %s' % apk_path 
            subprocess.call(cmd, shell=True)
elif RM_STATUS == 2: 
            zip_file_name = self.project_path + '/../clean_app/' + os.path.basename(apk_path)[:-3] + 'zip' 
            smali_path = apk_path + '/smali' 
            self.zip_apk(smali_path, zip_file_name) 
            return zip_file_name `
```

and set RM_STATUS to 2.

**Comment by tmliu0606** [comment]
still not working.....:
self.zip_apk(smali_path, zip_file_name)
AttributeError: Detector instance has no attribute 'zip_apk'

**Comment by tmliu0606** [comment]
Still not working...:
self.zip_apk(smali_path, zip_file_name)
AttributeError: Detector instance has no attribute 'zip_apk'

**Comment by pkumza** [comment]
This functionality was implemented in some version but I deleted it after several versions.
I delete the libraries detected and then dump smali code into a *clean_app* folder. Maybe you could find a commit [6b2115] and try this version.
<hr>
I recommend you get a lib list with LibRadar2 and decompile the apk with Apktool. Then write a automatic script to delete smali files in libraries.

**Comment by tmliu0606** [comment]
Commit [6b2115] won't work either, I will try writing a script. 
Thank you very much.
