### ISSUE TITLE
Always empty output

### ISSUE THREAD

**Issue by singlewindy** [pkumza/LibRadar#26]
No matter which apk I choose, the script always returns empty set.
```
$ python LibRadar/libradar.py apks/com.flashlight.brightestflashlightpro.1.42.1.apk
[]
```

I think this may have something to do with my redis env.

If I run the following command, I can return the correct value. So I believe the redis.conf is configured correctly.

```
$ redis-cli
127.0.0.1:6379> keys *
1) "feature_weight"
2) "un_ob_cnt"
3) "feature_cnt"
4) "un_ob_pn"
```

However, the following script always returns empty list:

```
$ redis-cli -n 3
127.0.0.1:6379[3]> keys *
(empty list or set)
127.0.0.1:6379[3]>
```

I was using the LibRadarData.rdb from newly uploaded dataset-0410-19k.rdb.tar.gz.

```
$ ls -la
total 178816
drwxr-xr-x   4 Stan  staff       136 Apr 25 10:49 .
drwxr-xr-x  19 Stan  staff       646 Apr 25 10:48 ..
-rw-r--r--@  1 Stan  staff      6148 Apr 25 10:19 .DS_Store
-rw-r--r--   1 Stan  staff  91544212 Apr 25 09:22 LibRadarData.rdb
```

Do you know how to fix this problem? Thanks.

**Comment by pkumza** [comment]
Sorry for the inconvenience.
That's probably because you are using an *old version* of LibRadar but downloaded the latest LibRadarData.rdb
Please try
```
 git pull origin master 
```
to get the latest LibRadar.

**Comment by singlewindy** [comment]
Thanks for the reply. 
However, I'm actually using the latest version of LibRadar. So I don't think this is the problem.
I also tried both redis-3.2.8 and redis-3.2.0, and the result is the same.

**Comment by pkumza** [comment]
I don't use db 3,4,5,6... any more.
All I use in this version is db-0 and there're only 4 items.
1. "feature_weight"
2. "un_ob_cnt"
3. "feature_cnt"
4. "un_ob_pn"
Thus your Redis configuration should be right. 

I will check the LibRadar code later.

**Comment by pkumza** [comment]
Sorry, I still don't know how to solved as I can't reappear it.
Maybe you can try [LiteRadar](https://github.com/pkumza/LiteRadar), a lite version of LibRadar. Easy to use.

**Comment by singlewindy** [comment]
Great! Thanks for help.

**Comment by kaito233** [comment]
I meet this issue in lite version and find that there is no '__pycache__' folder in my literadar directory.

**Comment by kaito233** [comment]
I think that apk file must have 'asset' folder.
