### ISSUE TITLE
What‘s difference from "Professional use" as mentioned in "QuickStart.md" with usual use?

### ISSUE THREAD

**Issue by daydayup1** [pkumza/LibRadar#27]
If I just want to detect third-party libraries in a large number of apk precisely, should I do as written in "For Professional use"?

**Comment by pkumza** [comment]
If you want to extract lib features from a large potion of APP(more than 1 million APKs) to get a giant dataset by yourself, you could read "professional use".
If you want to check some apps, just ignore it.
