### ISSUE TITLE
Library definition

### ISSUE THREAD

**Issue by IzzySoft** [pkumza/LibRadar#28]
I'm not on the latest code here (too many dependencies for me :smile_cat: ), and the database isn't in there anyway AFAIR – but you might wish to check 6 library definitions which are probably wrong:

<pre>
-{"dn": 135, "lib": "pa;Bump pay;", "sp": "com/bumptech/glide/disklrucache", "bh": 343072, "btc": 265, "btn": 73, "pn": "com/bump"}
+{"dn": 135, "lib": "da;Glide;https://github.com/bumptech/glide", "sp": "com/bumptech/glide/disklrucache", "bh": 343072, "btc": 265, "btn": 73, "pn": "com/bumptech/glide"}
-{"dn": 102, "lib": "pa;Bump pay;", "sp": "com/bumptech/glide/gifencoder", "bh": 134926, "btc": 59, "btn": 25, "pn": "com/bump"}
+{"dn": 102, "lib": "da;Glide;https://github.com/bumptech/glide", "sp": "com/bumptech/glide/gifencoder", "bh": 134926, "btc": 59, "btn": 25, "pn": "com/bumptech/glide"}
-{"dn": 117, "lib": "pa;Bump pay;", "sp": "com/bumptech/glide/f", "bh": 24660, "btc": 31, "btn": 19, "pn": "com/bump"}
+{"dn": 117, "lib": "da;Glide;https://github.com/bumptech/glide", "sp": "com/bumptech/glide/f", "bh": 24660, "btc": 31, "btn": 19, "pn": "com/bumptech/glide"}
-{"dn": 105, "lib": "pa;Bump pay;", "sp": "com/bumptech/glide/load/resource/transcode", "bh": 15933, "btc": 22, "btn": 13, "pn": "com/bump"}
+{"dn": 105, "lib": "da;Glide;https://github.com/bumptech/glide", "sp": "com/bumptech/glide/load/resource/transcode", "bh": 15933, "btc": 22, "btn": 13, "pn": "com/bumptech/glide"}
-{"dn": 166, "lib": "pa;Bump pay;", "sp": "com/bumptech/glide/e/d/e", "bh": 14882, "btc": 24, "btn": 9, "pn": "com/bump"}
+{"dn": 166, "lib": "da;Glide;https://github.com/bumptech/glide", "sp": "com/bumptech/glide/e/d/e", "bh": 14882, "btc": 24, "btn": 9, "pn": "com/bumptech/glide"}
-{"dn": 172, "lib": "pa;Bump pay;", "sp": "com/bumptech/glide/g", "bh": 8881, "btc": 12, "btn": 7, "pn": "com/bump"}
+{"dn": 172, "lib": "da;Glide;https://github.com/bumptech/glide", "sp": "com/bumptech/glide/g", "bh": 8881, "btc": 12, "btn": 7, "pn": "com/bumptech/glide"}
</pre>

**Comment by pkumza** [comment]
So that's still version 1? 
Maybe you could make a PR on "V1" branch?

**Comment by IzzySoft** [comment]
OK, there you go: #29 created :)

**Comment by pkumza** [comment]
Thanks~ 👍

**Comment by IzzySoft** [comment]
Anytime! So as it's obviously still helpful committing against V1, there might be future library updates from me here. Guess you'll transfer them somehow to the latest branch then?
