### ISSUE TITLE
matching algorithm

### ISSUE THREAD

**Issue by pkumza** [pkumza/LibRadar#39]
do not match `com/bump` with `com/bumptech/glide` again!

* [x] Solve the Matching bug.

**Comment by pkumza** [comment]
* [ ] Solve the Matching bug.

**Comment by IzzySoft** [comment]
In my "afterburner" (for libraries not recognized by V1) I use a regex for that, which matches the definition only if followed by a `/` (i.e. the match is a sub-path of the module) or "end of path" (i.e. "exact match").
