### ISSUE TITLE
Tagging FasterXML

### ISSUE THREAD

**Issue by IzzySoft** [pkumza/LibRadar#4]
I suspect some mis-tagging: what currently is tagged as "FasterXML" (`com/fasterxml`) at least at several places is rather the [Jackson Project](https://github.com/FasterXML/jackson) (`com/fasterxml/jackson`) – see e.g. [jackson-core](https://github.com/FasterXML/jackson-core) (`com/fasterxml/jackson/core`). Besides, the website fasterxml.com does not resolve. Could you please cross-check that?

Also, there's a related project (`com/shaded/fasterxml/jackson`). Not sure how that should be tagged, so for now I skip it.

**Comment by IzzySoft** [comment]
Another pointer on that can be found at AppBrain, which has this as [FasterXML Jackson](http://www.appbrain.com/stats/libraries/details/fasterxml_jackson/fasterxml-jackson), pointing to the same Github presence (https://github.com/FasterXML).

**Comment by pkumza** [comment]
Now in version 2.1.0, It is easier to tag them in https://github.com/pkumza/LibRadar/blob/master/LibRadar/Data/IntermediateData/tag_rules.csv
