### ISSUE TITLE
Dataset is not available

### ISSUE THREAD

**Issue by yoavst** [pkumza/LibRadar#45]
Where is the full dataset stored?

**Comment by pkumza** [comment]
Highly suggest you to try [LiteRadar](https://github.com/pkumza/LiteRadar), a lite version of LibRadar that with no compromise to library number.

Or try [online detecting](http://radar.pkuos.org)

As github only accepts files that less than 100MB, I could only upload a small set of data as [dataset](https://github.com/pkumza/Data_for_LibRadar/blob/master/LibRadarData0410.rdb)

The latest dataset(of more than 2,400,000 apps) has reached 4.4GB, that I can't afford a fast CDN. I've upload a 2.5GB dataset (of 1 million apps) to [Baiduyun](https://pan.baidu.com/s/1miTzdMg), but I am not sure about your network speed to China.

**Comment by yoavst** [comment]
Thank for your answer!

**Comment by yoavst** [comment]
Just a small question @pkumza , What is the difference between the full and lite one?

**Comment by pkumza** [comment]
Please check issue 1 of LiteRadar.😃




On 06/15/2017 19:29, Yoav Sternberg wrote:

Just a small question @pkumza , What is the difference between the full and lite one?

**Comment by yoavst** [comment]
Sorry for interrupting you, but it seems almost impossible to download anything from Baidu if you are not Chinese. Can you please upload it to something more international?

Thanks again!

**Comment by pkumza** [comment]
Size-optimized dataset is available at
https://www.dropbox.com/s/w31gig6msdo3cdy/dump-20170515-shrink.rdb.tar.gz?dl=0

See [docs/QuickStart.md](https://github.com/pkumza/LibRadar/blob/master/docs/QuickStart.md) for detailed installation steps.

**Comment by yoavst** [comment]
I'm running LibRadar with the full dataset from dropbox and it returns empty data `[]`.LiteRadar works. Any idea?

**Comment by pkumza** [comment]
Please check that if you are using the latest version first. 
The features I use is different in recent commits.

**Comment by yoavst** [comment]
Repo is up to date.

**Comment by pkumza** [comment]
Interesting... I've tried again and the shrink data works well.
<hr>
As you are using Redis, you must have installed `redis-cli`.
try it!

```bash
$ redis-cli
127.0.0.1:6379> select 2
OK
127.0.0.1:6379[2]> keys *
1) "un_ob_pn"
2) "feature_weight"
3) "un_ob_cnt"
4) "feature_cnt"
```

Please check if your output is just the same.

**Comment by yoavst** [comment]
```
127.0.0.1:6379[2]> keys *
1) "feature_cnt"
2) "feature_weight"
3) "un_ob_pn"
4) "un_ob_cnt"
```

**Comment by pkumza** [comment]
Oh yes, your redis works well too. =_=

**Comment by pkumza** [comment]
Sorry, I've no idea what happened to LibRadar.

I'll test the steps of my `QuickStart.md` in a purely new machine soon. And I'd better create a docker image for LibRadar latter.

**Comment by yoavst** [comment]
Thanks!

**Comment by pkumza** [comment]
I've checked a pure environment and it works well too.

I got a reason that `Redis` needs several seconds to listen a port as the database is large. How about checking DB settings in `_settings.py` and trying it again?

**Comment by yoavst** [comment]
The settings seems OK. I'm running it on latest OS X.

**Comment by yoavst** [comment]
Seems to be an OS X problem, works great on Ubuntu VM.

**Comment by pkumza** [comment]
LibRadar is deployed on Linux now. However it is always developed on OS X.  🙉
It works well on my Mac too. 🐵
There's gotta be something wrong with your macOS Env. 🙈

**Comment by jawz101** [comment]
@pkumza Have you heard of Digital Ocean?  The cheapest Droplet costs $5/month USD.  It's not a high spec'd machine but you get 1 Terabyte of transfer per month.

https://www.digitalocean.com/pricing/#droplet

**Comment by AlexKoshulyan** [comment]
The link https://www.dropbox.com/s/w31gig6msdo3cdy/dump-20170515-shrink.rdb.tar.gz?dl=0 is broken by now.

**Comment by pkumza** [comment]
@AlexKoshulyan 
Yes, it is broken.
Could you have a try for [https://www.dropbox.com/s/ljtzw74twt8xgy6/d.tar.gz?dl=0](https://www.dropbox.com/s/ljtzw74twt8xgy6/d.tar.gz?dl=0) ?

**Comment by AlexKoshulyan** [comment]
Fine
