### ISSUE TITLE
Redis dump broken link on the documentation

### ISSUE THREAD

**Issue by ametade** [pkumza/LibRadar#55]
Hi,

The redis dump link on the quick start documentation page (https://github.com/pkumza/LibRadar/blob/master/docs/QuickStart.md) is not working any more:
https://www.dropbox.com/s/w31gig6msdo3cdy/dump-20170515-shrink.rdb.tar.gz?dl=0

Could you please update it?

By the way, is the data on that redis dump the same as in the lite_datasetfile .csv file?

Thank you and best regards,
Rodrigo

**Comment by pkumza** [comment]
Sorry, I don't have enough dropbox space.
You could try LiteRadar, they are almost the same.

**Comment by ametade** [comment]
Thank you. I'll take a look into LiteRadar.
