### ISSUE TITLE
LibRadar isn't working 

### ISSUE THREAD

**Issue by MBus123** [pkumza/LibRadar#58]
I am using the latest rdb file (https://github.com/pkumza/Data_for_LibRadar/blob/master/LibRadarData0410.rdb) and the latest version of LibRadar. I configured it as described in the readme file, but i get always an 
empty output. This is not the case when i use LiteRadar. By looking in the code, 
i found that LibRadar is using besides db 0 and 1, db 2. 
`redis-cli -n 2` followed by `keys *` results in the following output: 
> (empty list or set)

Is it possible that you didn't upload the latest version of LibRadar?

**Comment by MBus123** [comment]
I found that the keys in the previous mentioned rdb file are just 32 characters long, so i assume it is still using md5 sums instead of sha256. Is their any updated file?

**Comment by pkumza** [comment]
https://github.com/pkumza/Data_for_LibRadar/blob/master/LibRadarData0410.rdb is not the latest rdb file because the latest rdb file is very large. (several GB)

I can't find a stable repository for my Large file... Every time a upload a file, the link breaks after several month.

Could you please try github.com/pkumza/LiteRadar? They are almost the same.

**Comment by MBus123** [comment]
I created a new rbd file from lite_dataset_10.csv using the following python script:


```
import redis

DB_HOST = 'localhost'
DB_PORT = 6379
DB_ID = 0
DB_PSWD = ''

DB_FEATURE_CNT = 'feature_cnt'
DB_FEATURE_WEIGHT = 'feature_weight'
DB_UN_OB_PN = 'un_ob_pn'
DB_UN_OB_CNT = 'un_ob_cnt'

db = redis.StrictRedis(host=DB_HOST,port=DB_PORT, db=0, password=DB_PSWD)
db.flushall()
f = open('lite_dataset_10.csv', 'r')
for line in f:
    array = line.split(",")
    print (line)
    db.hset(DB_UN_OB_PN, array[0], array[4])
    db.hset(DB_FEATURE_CNT, array[0], array[1])
    db.hset(DB_UN_OB_CNT, array[0], array[3])
    db.hset(DB_FEATURE_WEIGHT, array[0], array[2])
db.save()
```

**Comment by pkumza** [comment]
There's no feature data in lite_dataset_10.csv.🤔
