### ISSUE TITLE
Redis integration

### ISSUE THREAD

**Issue by A-AFTAHI** [pkumza/LibRadar#59]
i cloned LIbradar in my kali linux machine. then i installed redis 3.2.11 on my machine but still when i run libradar.py i got this error : 

 Traceback (most recent call last):
  File "libradar.py", line 25, in <module>
    import dex_tree
  File "/root/LibRadar/LibRadar/dex_tree.py", line 27, in <module>
    import redis
ImportError: No module named redis

i wonder do i have to download the redis and put it inside the Liradar folder?or there is an other way to make it work ?

edit: i just add the redis inside Libradar/Libradar and still face the same issue. anyone help please?

**Comment by A-AFTAHI** [comment]
Dropbox link to LibRadarData.rdb is not working

**Comment by pkumza** [comment]
Answer 1:

```
pip install redis
```

------

Answer 2:
Please try [LiteRadar](https://github.com/pkumza/Literadar) if it could meet your need.

**Comment by pkumza** [comment]
@A-AFTAHI I uploaded a new one, would you like to try [Dropbox Link](https://www.dropbox.com/s/ljtzw74twt8xgy6/d.tar.gz?dl=0)?
