### ISSUE TITLE
Link rot "http://lxwiki.oss-cn-beijing.aliyuncs.com/lite_dataset_10.csv"

### ISSUE THREAD

**Issue by Kractal** [pkumza/LibRadar#63]
Link rot "http://lxwiki.oss-cn-beijing.aliyuncs.com/lite_dataset_10.csv" in this page "https://github.com/pkumza/LibRadar/blob/master/docs/QuickStart.md".
![default](https://user-images.githubusercontent.com/22289452/50212448-11dae480-03b6-11e9-8219-cfc68fd6853e.png)

**Comment by pkumza** [comment]
Thanks, I will remove it from the page.
please use Github's resource
